name: 'Build Go Binary'
description: 'Build Go Binary'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Build Go binary with static linking
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o bin/gf-emailparser-binary
      shell: bash
      working-directory: ./flightalerts/gf-emailparser/cmd