name: 'Deploy_to_droplet'
description: 'Deploy a Go binary to a single DigitalOcean Droplet'

inputs:
  do_ssh_private_key:
    description: 'SSH private key for DigitalOcean'
    required: true
  droplet_ip:
    description: 'DigitalOcean Droplet IP'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.do_ssh_private_key }}

    - name: Deploy to DigitalOcean
      env:
        DROPLET_IP: ${{ inputs.droplet_ip }}
      run: |
        # Create the necessary directories
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "mkdir -p /var/www/gf-emailparser /usr/local/bin /root/gf-emailparser"

        # Create a placeholder .env file
        echo "PLACEHOLDER=true" | ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "cat > /root/gf-emailparser/.env"

        # Stop the service if it exists
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
        if systemctl list-unit-files | grep -q gf-emailparser.service; then
            sudo systemctl stop gf-emailparser && echo 'Service stopped successfully'
        else
            echo 'gf-emailparser.service does not exist'
        fi
        "

        # Remove the old binary
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
        if [ -f /usr/local/bin/gf-emailparser-binary ]; then
            sudo rm -f /usr/local/bin/gf-emailparser-binary && echo 'Old binary removed successfully'
        else
            echo 'gf-emailparser-binary does not exist in /usr/local/bin'
        fi
        "

        # Deploy the Go binary
        echo "Uploading Go binary to $DROPLET_IP..."
        scp -o StrictHostKeyChecking=no ./gf-emailparser/cmd/bin/gf-emailparser-binary root@$DROPLET_IP:/usr/local/bin/gf-emailparser-binary

        # Set the correct permissions for the binary
        echo 'Setting permissions for the binary'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "chmod +x /usr/local/bin/gf-emailparser-binary"

        # Create log files
        echo 'Creating log files'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "touch /root/gf-emailparser/logfile.log /root/gf-emailparser/error.log"

        # Upload the systemd service file
        echo 'Uploading systemd service file'
        scp -o StrictHostKeyChecking=no ./configs/systemd/system/gf-emailparser.service root@$DROPLET_IP:/etc/systemd/system/gf-emailparser.service

        # Set correct permissions for the systemd service file
        echo 'Setting permissions for the systemd service file'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "chmod 644 /etc/systemd/system/gf-emailparser.service"

        # Set environment variables for the service
        echo 'Setting environment variables for the service'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP << 'EOF'
        export CLIENT_ID=${{ secrets.CLIENT_ID }}
        export CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        export REDIRECT_URL=${{ vars.REDIRECT_URL }}
        export SPREADSHEET_ID=${{ vars.SPREADSHEET_ID }}
        EOF

        # Check and set permissions for tokens.json if it exists
        echo 'Checking and setting permissions for tokens.json'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP << 'EOF'
        if [ -f /root/gf-emailparser/tokens.json ]; then
            echo 'tokens.json exists, setting permissions'
            sudo chmod 600 /root/gf-emailparser/tokens.json
        else
            echo 'tokens.json does not exist'
        fi
        EOF

        # Enable and start the service
        echo 'Enabling and starting the service'
        ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "
        systemctl daemon-reload && systemctl enable gf-emailparser.service && systemctl start gf-emailparser.service"
      shell: bash