routes = [
    ('MAN', 'Aberdeen'), ('Aberdeen', 'MAN'),
    ('MAN', 'Abu Dhabi'), ('Abu Dhabi', 'MAN'),
    ('MAN', 'Addis Ababa'), ('Addis Ababa', 'MAN'),
    ('MAN', 'Agadir'), ('Agadir', 'MAN'),
    ('MAN', 'Alicante'), ('Alicante', 'MAN'),
    ('MAN', 'Almeria'), ('Almeria', 'MAN'),
    ('MAN', 'Amman'), ('Amman', 'MAN'),
    ('MAN', 'Amsterdam'), ('Amsterdam', 'MAN'),
    ('MAN', 'Antalya'), ('Antalya', 'MAN'),
    ('MAN', 'Antigua'), ('Antigua', 'MAN'),
    ('MAN', 'Athens'), ('Athens', 'MAN'),
    ('MAN', 'Atlanta'), ('Atlanta', 'MAN'),
    ('MAN', 'Bahrain'), ('Bahrain', 'MAN'),
    ('MAN', 'Banjul'), ('Banjul', 'MAN'),
    ('MAN', 'Barbados'), ('Barbados', 'MAN'),
    ('MAN', 'Barcelona'), ('Barcelona', 'MAN'),
    ('MAN', 'Basel'), ('Basel', 'MAN'),
    ('MAN', 'Beijing'), ('Beijing', 'MAN'),
    ('MAN', 'Belfast'), ('Belfast', 'MAN'),
    ('MAN', 'Bergen'), ('Bergen', 'MAN'),
    ('MAN', 'Bergerac'), ('Bergerac', 'MAN'),
    ('MAN', 'Berlin'), ('Berlin', 'MAN'),
    ('MAN', 'Beziers'), ('Beziers', 'MAN'),
    ('MAN', 'Bilbao'), ('Bilbao', 'MAN'),
    ('MAN', 'Billund'), ('Billund', 'MAN'),
    ('MAN', 'Boa Vista'), ('Boa Vista', 'MAN'),
    ('MAN', 'Bodrum'), ('Bodrum', 'MAN'),
    ('MAN', 'Bologna'), ('Bologna', 'MAN'),
    ('MAN', 'Bordeaux'), ('Bordeaux', 'MAN'),
    ('MAN', 'Bratislava'), ('Bratislava', 'MAN'),
    ('MAN', 'Bridgetown'), ('Bridgetown', 'MAN'),
    ('MAN', 'Brindisi'), ('Brindisi', 'MAN'),
    ('MAN', 'Brussels'), ('Brussels', 'MAN'),
    ('MAN', 'Bucharest'), ('Bucharest', 'MAN'),
    ('MAN', 'Budapest'), ('Budapest', 'MAN'),
    ('MAN', 'Cairo'), ('Cairo', 'MAN'),
    ('MAN', 'Cancun'), ('Cancun', 'MAN'),
    ('MAN', 'Carcassonne'), ('Carcassonne', 'MAN'),
    ('MAN', 'Casablanca'), ('Casablanca', 'MAN'),
    ('MAN', 'Catania'), ('Catania', 'MAN'),
    ('MAN', 'Chambery'), ('Chambery', 'MAN'),
    ('MAN', 'Chania'), ('Chania', 'MAN'),
    ('MAN', 'Charleroi'), ('Charleroi', 'MAN'),
    ('MAN', 'Cologne'), ('Cologne', 'MAN'),
    ('MAN', 'Copenhagen'), ('Copenhagen', 'MAN'),
    ('MAN', 'Corfu'), ('Corfu', 'MAN'),
    ('MAN', 'Cork'), ('Cork', 'MAN'),
    ('MAN', 'Dalaman'), ('Dalaman', 'MAN'),
    ('MAN', 'Doha'), ('Doha', 'MAN'),
    ('MAN', 'Dubai'), ('Dubai', 'MAN'),
    ('MAN', 'Dublin'), ('Dublin', 'MAN'),
    ('MAN', 'Dubrovnik'), ('Dubrovnik', 'MAN'),
    ('MAN', 'Dusseldorf'), ('Dusseldorf', 'MAN'),
    ('MAN', 'Eindhoven'), ('Eindhoven', 'MAN'),
    ('MAN', 'Enfidha'), ('Enfidha', 'MAN'),
    ('MAN', 'Faro'), ('Faro', 'MAN'),
    ('MAN', 'Frankfurt'), ('Frankfurt', 'MAN'),
    ('MAN', 'Fuerteventura'), ('Fuerteventura', 'MAN'),
    ('MAN', 'Gdansk'), ('Gdansk', 'MAN'),
    ('MAN', 'Geneva'), ('Geneva', 'MAN'),
    ('MAN', 'Genoa'), ('Genoa', 'MAN'),
    ('MAN', 'Gibraltar'), ('Gibraltar', 'MAN'),
    ('MAN', 'Girona'), ('Girona', 'MAN'),
    ('MAN', 'Goa'), ('Goa', 'MAN'),
    ('MAN', 'Gothenburg'), ('Gothenburg', 'MAN'),
    ('MAN', 'Gran Canaria'), ('Gran Canaria', 'MAN'),
    ('MAN', 'Grenoble'), ('Grenoble', 'MAN'),
    ('MAN', 'Guernsey'), ('Guernsey', 'MAN'),
    ('MAN', 'Hamburg'), ('Hamburg', 'MAN'),
    ('MAN', 'Helsinki'), ('Helsinki', 'MAN'),
    ('MAN', 'Heraklion'), ('Heraklion', 'MAN'),
    ('MAN', 'Hong Kong'), ('Hong Kong', 'MAN'),
    ('MAN', 'Houston'), ('Houston', 'MAN'),
    ('MAN', 'Hurghada'), ('Hurghada', 'MAN'),
    ('MAN', 'Ibiza'), ('Ibiza', 'MAN'),
    ('MAN', 'Innsbruck'), ('Innsbruck', 'MAN'),
    ('MAN', 'Inverness'), ('Inverness', 'MAN'),
    ('MAN', 'Isle of Man'), ('Isle of Man', 'MAN'),
    ('MAN', 'Istanbul'), ('Istanbul', 'MAN'),
    ('MAN', 'Izmir'), ('Izmir', 'MAN'),
    ('MAN', 'Jeddah'), ('Jeddah', 'MAN'),
    ('MAN', 'Jersey'), ('Jersey', 'MAN'),
    ('MAN', 'Kalamata'), ('Kalamata', 'MAN'),
    ('MAN', 'Katowice'), ('Katowice', 'MAN'),
    ('MAN', 'Kavala'), ('Kavala', 'MAN'),
    ('MAN', 'Kefalonia'), ('Kefalonia', 'MAN'),
    ('MAN', 'Kerry'), ('Kerry', 'MAN'),
    ('MAN', 'Klagenfurt'), ('Klagenfurt', 'MAN'),
    ('MAN', 'Kittila'), ('Kittila', 'MAN'),
    ('MAN', 'Knock'), ('Knock', 'MAN'),
    ('MAN', 'Kos'), ('Kos', 'MAN'),
    ('MAN', 'Krakow'), ('Krakow', 'MAN'),
    ('MAN', 'Kuusamo'), ('Kuusamo', 'MAN'),
    ('MAN', 'Kuwait'), ('Kuwait', 'MAN'),
    ('MAN', 'La Palma'), ('La Palma', 'MAN'),
    ('MAN', 'La Rochelle'), ('La Rochelle', 'MAN'),
    ('MAN', 'Lanzarote'), ('Lanzarote', 'MAN'),
    ('MAN', 'Larnaca'), ('Larnaca', 'MAN'),
    ('MAN', 'Limoges'), ('Limoges', 'MAN'),
    ('MAN', 'Lisbon'), ('Lisbon', 'MAN'),
    ('MAN', 'London'), ('London', 'MAN'),
    ('MAN', 'Londonderry'), ('Londonderry', 'MAN'),
    ('MAN', 'Luxembourg'), ('Luxembourg', 'MAN'),
    ('MAN', 'Luxor'), ('Luxor', 'MAN'),
    ('MAN', 'Lyon'), ('Lyon', 'MAN'),
    ('MAN', 'Madeira'), ('Madeira', 'MAN'),
    ('MAN', 'Madrid'), ('Madrid', 'MAN'),
    ('MAN', 'Mahon, Menorca'), ('Mahon, Menorca', 'MAN'),
    ('MAN', 'Malaga'), ('Malaga', 'MAN'),
    ('MAN', 'Malta'), ('Malta', 'MAN'),
    ('MAN', 'Marrakech'), ('Marrakech', 'MAN'),
    ('MAN', 'Marseille'), ('Marseille', 'MAN'),
    ('MAN', 'Milan'), ('Milan', 'MAN'),
    ('MAN', 'Montego Bay'), ('Montego Bay', 'MAN'),
    ('MAN', 'Montenegro'), ('Montenegro', 'MAN'),
    ('MAN', 'Munich'), ('Munich', 'MAN'),
    ('MAN', 'Murcia'), ('Murcia', 'MAN'),
    ('MAN', 'Mykonos'), ('Mykonos', 'MAN'),
    ('MAN', 'Mytilene'), ('Mytilene', 'MAN'),
    ('MAN', 'Nantes'), ('Nantes', 'MAN'),
    ('MAN', 'Naples'), ('Naples', 'MAN'),
    ('MAN', 'New York'), ('New York', 'MAN'),
    ('MAN', 'Newquay'), ('Newquay', 'MAN'),
    ('MAN', 'Nice'), ('Nice', 'MAN'),
    ('MAN', 'Olbia'), ('Olbia', 'MAN'),
    ('MAN', 'Orlando'), ('Orlando', 'MAN'),
    ('MAN', 'Oslo'), ('Oslo', 'MAN'),
    ('MAN', 'Palma, Majorca'), ('Palma, Majorca', 'MAN'),
    ('MAN', 'Paphos'), ('Paphos', 'MAN'),
    ('MAN', 'Paris'), ('Paris', 'MAN'),
    ('MAN', 'Phuket'), ('Phuket', 'MAN'),
    ('MAN', 'Pisa'), ('Pisa', 'MAN'),
    ('MAN', 'Podgorica'), ('Podgorica', 'MAN'),
    ('MAN', 'Porto'), ('Porto', 'MAN'),
    ('MAN', 'Poznan'), ('Poznan', 'MAN'),
    ('MAN', 'Prague'), ('Prague', 'MAN'),
    ('MAN', 'Preveza'), ('Preveza', 'MAN'),
    ('MAN', 'Puerto Vallarta'), ('Puerto Vallarta', 'MAN'),
    ('MAN', 'Pula'), ('Pula', 'MAN'),
    ('MAN', 'Punta Cana'), ('Punta Cana', 'MAN'),
    ('MAN', 'Reus'), ('Reus', 'MAN'),
    ('MAN', 'Reykjavik'), ('Reykjavik', 'MAN'),
    ('MAN', 'Rhodes'), ('Rhodes', 'MAN'),
    ('MAN', 'Riga'), ('Riga', 'MAN'),
    ('MAN', 'Rome'), ('Rome', 'MAN'),
    ('MAN', 'Rzeszow'), ('Rzeszow', 'MAN'),
    ('MAN', 'Sal'), ('Sal', 'MAN'),
    ('MAN', 'Salzburg'), ('Salzburg', 'MAN'),
    ('MAN', 'Santander'), ('Santander', 'MAN'),
    ('MAN', 'Santorini'), ('Santorini', 'MAN'),
    ('MAN', 'Seville'), ('Seville', 'MAN'),
    ('MAN', 'Shanghai'), ('Shanghai', 'MAN'),
    ('MAN', 'Shannon'), ('Shannon', 'MAN'),
    ('MAN', 'Sharm el Sheikh'), ('Sharm el Sheikh', 'MAN'),
    ('MAN', 'Shetland'), ('Shetland', 'MAN'),
    ('MAN', 'Singapore'), ('Singapore', 'MAN'),
    ('MAN', 'Skiathos'), ('Skiathos', 'MAN'),
    ('MAN', 'Sofia'), ('Sofia', 'MAN'),
    ('MAN', 'Southampton'), ('Southampton', 'MAN'),
    ('MAN', 'Split'), ('Split', 'MAN'),
    ('MAN', 'Stavanger'), ('Stavanger', 'MAN'),
    ('MAN', 'Stockholm'), ('Stockholm', 'MAN'),
    ('MAN', 'Tel Aviv'), ('Tel Aviv', 'MAN'),
    ('MAN', 'Tenerife'), ('Tenerife', 'MAN'),
    ('MAN', 'Thessalonika'), ('Thessalonika', 'MAN'),
    ('MAN', 'Tivat'), ('Tivat', 'MAN'),
    ('MAN', 'Toronto'), ('Toronto', 'MAN'),
    ('MAN', 'Toulouse'), ('Toulouse', 'MAN'),
    ('MAN', 'Trapani'), ('Trapani', 'MAN'),
    ('MAN', 'Treviso'), ('Treviso', 'MAN'),
    ('MAN', 'Trondheim'), ('Trondheim', 'MAN'),
    ('MAN', 'Turin'), ('Turin', 'MAN'),
    ('MAN', 'Valencia'), ('Valencia', 'MAN'),
    ('MAN', 'Varadero'), ('Varadero', 'MAN'),
    ('MAN', 'Venice'), ('Venice', 'MAN'),
    ('MAN', 'Verona'), ('Verona', 'MAN'),
    ('MAN', 'Vienna'), ('Vienna', 'MAN'),
    ('MAN', 'Warsaw'), ('Warsaw', 'MAN'),
    ('MAN', 'Wroclaw'), ('Wroclaw', 'MAN'),
    ('MAN', 'Zadar'), ('Zadar', 'MAN'),
    ('MAN', 'Zagreb'), ('Zagreb', 'MAN'),
    ('MAN', 'Zakynthos'), ('Zakynthos', 'MAN'),
    ('MAN', 'Zurich'), ('Zurich', 'MAN')
]