name: Deploy Email Parser

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go binary with static linking
      uses: ./.github/actions/build_go_binary

    - name: Deploy Go binary to Digital Ocean
      uses: ./.github/actions/deploy_go_to_do
      with:
        do_ssh_private_key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        droplet_ip: ${{ secrets.DROPLET_IP }}
